import React from 'react';
import { parseRawText } from './lib/parser';
import { graphToCSV } from './lib/serializer';
import { SAMPLE_FAMILY_TEXT } from './lib/sampleData';
import { Header } from './components/Header';
import { Visualizer } from './components/Visualizer';
import { PasteModal } from './components/PasteModal';
import { PersonModal } from './components/PersonModal';
import { EditPersonModal } from './components/EditPersonModal';
import { AddRelativeModal } from './components/AddRelativeModal';
import { GoogleSyncModal } from './components/GoogleSyncModal';
import { QRCodeModal } from './components/QRCodeModal';
import { extractTreeFromCurrentUrl } from './lib/qrCodec';
import { toPng } from 'html-to-image';
import { CloudUpload, AlertCircle, Loader2 } from 'lucide-react';


import { useFamilyGraph } from './hooks/useFamilyGraph';
import { useGoogleSync } from './hooks/useGoogleSync';
import { useAppNavigation } from './hooks/useAppNavigation';
import { useToast } from './hooks/useToast';
import { ToastContainer } from './components/Toast';

export const App: React.FC = () => {
  // Use custom hooks
  const {
    graph,
    setTree,
    savePerson,
    deletePerson,
    addPerson
  } = useFamilyGraph();

  const {
    connectedSheet,
    setConnectedSheet,
    accessToken,
    setAccessToken,
    isSyncing,
    hasUnsavedChanges,
    syncError,
    handleQuickSync,
    disconnectSheet,
    markAsSynced
  } = useGoogleSync(graph);

  const {
    isPasteModalOpen,
    isGoogleModalOpen,
    isQRModalOpen,
    selectedPerson,
    editingPerson,
    addRelativeState,
    searchQuery,
    setSearchQuery,
    modalDepth,
    navigateTo,
    closeActiveModal,
    setSelectedPerson
  } = useAppNavigation(graph);

  const { toasts, showToast, dismissToast } = useToast();



  // Check URL on load for encoded graph
  React.useEffect(() => {
    const encodedGraph = extractTreeFromCurrentUrl();
    if (encodedGraph) {
      setTree(encodedGraph);
      markAsSynced(encodedGraph); // Reset sync state for new graph
      // Clean up encoded data from URL while preserving other params (e.g. lang=en)
      const url = new URL(window.location.href);
      url.searchParams.delete('qr-v0');
      url.searchParams.delete('d');
      url.searchParams.delete('redirect');
      if (url.hash.includes('view/qr-v0/')) {
        url.hash = '';
      }
      window.history.replaceState({}, '', url.toString());
    }
  }, []); // Run once

  // Handle Raw Text Parse (from Paste modal)
  const handleParseText = (rawText: string): boolean => {
    try {
      const parsedGraph = parseRawText(rawText);
      setTree(parsedGraph);
      navigateTo({}, true, parsedGraph);
      showToast('গ্রাফ সফলভাবে আপডেট করা হয়েছে!', 'success');
      return true;
    } catch (err) {
      console.error(err);
      return false;
    }
  };



  // Clear Graph
  const handleNewTree = () => {
    const emptyGraph = { people: {} };
    setTree(emptyGraph);
    disconnectSheet();
    markAsSynced(emptyGraph);
    navigateTo({}, true, emptyGraph);
  };

  // Load Sample
  const handleLoadSample = () => {
    const sample = parseRawText(SAMPLE_FAMILY_TEXT);
    setTree(sample);
    disconnectSheet();
    markAsSynced(sample);
    navigateTo({}, true, sample);
  };

  const handleSearchChange = (q: string) => {
    setSearchQuery(q);
    const url = new URL(window.location.href);
    if (q) url.searchParams.set('q', q);
    else url.searchParams.delete('q');
    window.history.replaceState({ modalDepth }, '', url.toString());
  };

    const handleExportViewport = async () => {
    const visualizerEl = document.querySelector('main > div') as HTMLElement;
    if (!visualizerEl) return;

    // Inject watermark for viewport export
    const watermark = document.createElement('div');
    watermark.innerText = 'Generated by bonsho-bd.github.io';
    watermark.style.position = 'absolute';
    watermark.style.bottom = '20px';
    watermark.style.right = '20px';
    watermark.style.color = 'rgba(0, 0, 0, 0.25)';
    watermark.style.fontFamily = 'system-ui, sans-serif';
    watermark.style.fontSize = '16px';
    watermark.style.fontWeight = 'bold';
    watermark.style.pointerEvents = 'none';
    watermark.style.userSelect = 'none';
    watermark.style.zIndex = '50';
    watermark.id = 'temp-watermark-viewport';

    visualizerEl.appendChild(watermark);

    // Wait for reflow and image load
    await new Promise(r => setTimeout(r, 150));

    try {
      const dataUrl = await toPng(visualizerEl, { quality: 1, pixelRatio: 2, skipFonts: false });
      const link = document.createElement('a');
      link.download = 'bonsho-viewport.png';
      link.href = dataUrl;
      link.click();
    } catch (err) {
      showToast('ছবি তৈরি করতে সমস্যা হয়েছে।', 'error');
      console.error(err);
    } finally {
      const el = document.getElementById('temp-watermark-viewport');
      if (el) el.remove();
    }
  };

    const handleExportFullTree = async () => {
    const visualizerRoot = document.querySelector('main > div') as HTMLElement;

    if (!visualizerRoot) {
      showToast('ফ্যামিলি গ্রাফ খালি', 'info');
      return;
    }

    const nodes = document.querySelectorAll('.bonsho-node');
    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
    let found = false;
    nodes.forEach(node => {
      const el = node as HTMLElement;
      const left = parseFloat(el.style.left || '');
      const top = parseFloat(el.style.top || '');
      if (!isNaN(left) && !isNaN(top)) {
        if (left < minX) minX = left;
        if (left > maxX) maxX = left;
        if (top < minY) minY = top;
        if (top > maxY) maxY = top;
        found = true;
      }
    });

    if (!found) {
      minX = 0; minY = 0; maxX = 500; maxY = 500;
    }

    const padding = 150;
    const nodeWidth = 250;
    const nodeHeight = 150;
    const fullWidth = (maxX - minX) + nodeWidth + padding * 2;
    const fullHeight = (maxY - minY) + nodeHeight + padding * 2;

    const cloneRoot = visualizerRoot.cloneNode(true) as HTMLElement;
    cloneRoot.style.position = 'absolute';
    cloneRoot.style.top = '-9999px';
    cloneRoot.style.left = '-9999px';
    cloneRoot.style.width = `${fullWidth}px`;
    cloneRoot.style.height = `${fullHeight}px`;
    visualizerRoot.parentElement?.appendChild(cloneRoot);

    const cloneNodesContainer = cloneRoot.querySelector('.origin-top-left') as HTMLElement;
    const cloneSvgGroup = cloneRoot.querySelector('svg.pointer-events-none g') as SVGGElement;
    const cloneBgGrid = cloneRoot.querySelector('.canvas-bg') as HTMLElement;

    try {
      if (cloneNodesContainer) cloneNodesContainer.style.transform = `translate(${-minX + padding}px, ${-minY + padding}px) scale(1)`;
      if (cloneSvgGroup) cloneSvgGroup.setAttribute('transform', `translate(${-minX + padding}, ${-minY + padding}) scale(1)`);
      if (cloneBgGrid) {
        cloneBgGrid.style.backgroundPosition = `${-minX + padding}px ${-minY + padding}px`;
      }

      // Inject watermark directly into the clone
      const watermark = document.createElement('div');
      watermark.innerText = 'Generated by bonsho-bd.github.io';
      watermark.style.position = 'absolute';
      watermark.style.bottom = '40px';
      watermark.style.right = '40px';
      watermark.style.color = 'rgba(0, 0, 0, 0.25)';
      watermark.style.fontFamily = 'system-ui, sans-serif';
      watermark.style.fontSize = '32px';
      watermark.style.fontWeight = 'bold';
      watermark.style.pointerEvents = 'none';
      watermark.style.userSelect = 'none';
      watermark.style.zIndex = '50';
      cloneRoot.appendChild(watermark);

      // Wait for reflow
      await new Promise(r => setTimeout(r, 150));

      // Capture using the clone
      const dataUrl = await toPng(cloneRoot, {
        quality: 1,
        pixelRatio: 2,
        width: fullWidth,
        height: fullHeight,
        style: {
          width: `${fullWidth}px`,
          height: `${fullHeight}px`,
          position: 'absolute',
          top: '0',
          left: '0'
        },
        skipFonts: false
      });

      const link = document.createElement('a');
      link.download = 'bonsho-full-graph.png';
      link.href = dataUrl;
      link.click();
    } catch (err) {
      showToast('ছবি তৈরি করতে সমস্যা হয়েছে।', 'error');
      console.error(err);
    } finally {
      cloneRoot.remove();
    }
  };

  return (
    <div className="h-[100dvh] flex flex-col bg-slate-100 overflow-hidden">



      <Header
        onOpenPasteModal={() => navigateTo({ modal: 'clipboard' })}

        onOpenGoogleModal={() => navigateTo({ modal: 'google' })}
        onOpenQRCode={() => navigateTo({ modal: 'qr' })}
        onLoadSample={handleLoadSample}
        onNewTree={handleNewTree}
        onExportFullTree={handleExportFullTree}
        onExportViewport={handleExportViewport}
        onCopyToClipboard={() => {
          navigator.clipboard.writeText(graphToCSV(graph))
            .then(() => showToast('গ্রাফ ডেটা ক্লিপবোর্ডে কপি করা হয়েছে!', 'success'))
            .catch(() => showToast('কপি করতে সমস্যা হয়েছে।', 'error'));
        }}
        searchQuery={searchQuery}
        onSearchChange={handleSearchChange}
        totalPeopleCount={Object.keys(graph.people).length}
        connectedSheet={connectedSheet}
      />

      <main className="flex-1 relative">
        {hasUnsavedChanges && (
          <div className="absolute top-4 left-1/2 -translate-x-1/2 z-40 bg-white/95 backdrop-blur-sm border border-amber-200 shadow-xl rounded-2xl p-3 flex flex-col sm:flex-row items-center gap-3 animate-in slide-in-from-top-4">
            <div className="flex items-center gap-2 text-xs font-semibold text-amber-800">
              <AlertCircle className="w-4 h-4 text-amber-600" />
              <span>
                {syncError
                  ? `সেভ করতে সমস্যা হয়েছে: ${syncError}`
                  : 'গুগল শিটে কিছু পরিবর্তন সেভ করা বাকি আছে।'}
              </span>
            </div>
            <button
              onClick={handleQuickSync}
              disabled={isSyncing}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-emerald-600 hover:bg-emerald-700 active:scale-95 text-white rounded-lg text-xs font-bold transition shadow-sm whitespace-nowrap disabled:opacity-50"
            >
              {isSyncing ? (
                <>
                  <Loader2 className="w-3.5 h-3.5 animate-spin" />
                  সেভ হচ্ছে...
                </>
              ) : (
                <>
                  <CloudUpload className="w-3.5 h-3.5" />
                  গুগল শিটে সেভ করুন
                </>
              )}
            </button>
          </div>
        )}
        <Visualizer
          graph={graph}
          searchQuery={searchQuery}
          onSelectPerson={(p) => navigateTo({ person: p.id })}
          onAddChild={(p) => navigateTo({ person: p.id, add: 'child', target: p.id })}
          onAddSpouse={(p) => navigateTo({ person: p.id, add: 'spouse', target: p.id })}
          onAddPerson={() => {
            navigateTo({ add: 'person' });
          }}
        />
      </main>

      <PasteModal
        isOpen={isPasteModalOpen}
        onClose={closeActiveModal}
        onParseText={handleParseText}
        graph={graph}
      />

      <GoogleSyncModal
        isOpen={isGoogleModalOpen}
        onClose={closeActiveModal}
        graph={graph}
        onTreeLoaded={(newTree) => {
          setTree(newTree);
          markAsSynced(newTree);
          navigateTo({}, true, newTree);
        }}
        connectedSheet={connectedSheet}
        onSetConnectedSheet={setConnectedSheet}
        accessToken={accessToken}
        onSetAccessToken={setAccessToken}
      />

      <QRCodeModal
        isOpen={isQRModalOpen}
        onClose={closeActiveModal}
        graph={graph}
      />

      <PersonModal
        person={selectedPerson}
        graph={graph}
        isOpen={Boolean(selectedPerson) && !editingPerson && !addRelativeState.isOpen}
        onClose={() => {
          setSelectedPerson(null);
          closeActiveModal();
        }}
        onSelectPerson={(id) => navigateTo({ person: id })}
        onEditPerson={(p) => navigateTo({ person: p.id, edit: p.id })}
        onAddChild={(p) => navigateTo({ person: p.id, add: 'child', target: p.id })}
        onAddSpouse={(p) => navigateTo({ person: p.id, add: 'spouse', target: p.id })}
        canGoBack={modalDepth > 1}
        onBack={closeActiveModal}
      />

      <EditPersonModal
        person={editingPerson}
        isOpen={Boolean(editingPerson)}
        onClose={closeActiveModal}
        onSave={savePerson}
        onDeletePerson={deletePerson}
      />

      <AddRelativeModal
        person={addRelativeState.person}
        mode={addRelativeState.mode}
        graph={graph}
        isOpen={addRelativeState.isOpen}
        onClose={closeActiveModal}
        onAdd={(data) => {
          const newPerson = addPerson(data);
          if (newPerson) {
            showToast(`${newPerson.name} যোগ করা হয়েছে!`, 'success');
            navigateTo({ person: newPerson.id }, true);
          }
        }}
      />

      {/* Modern In-App Toast Notifications */}
      <ToastContainer toasts={toasts} onDismiss={dismissToast} />

    </div>
  );
};

export default App;
